Addition of new use case with a readiness probe in the replica sets section

diff --git a/30 - replicasets/36-nature-rs.yaml b/30 - replicasets/36-nature-rs.yaml
--- a/30 - replicasets/36-nature-rs.yaml
+++ b/30 - replicasets/36-nature-rs.yaml
@@ -38,6 +38,67 @@ data:
       }
 
 ---
+apiVersion: v1
+kind: Pod
+metadata:
+  name: internal-server
+  namespace: nature-rs-system
+  labels:
+    app: internal-server
+spec:
+  initContainers:
+    - name: data-getter
+      image: docker.io/busybox:1.37.0
+      imagePullPolicy: IfNotPresent
+      command:
+        - bin/sh
+        - -c
+        - |
+          cd /data01
+          wget -o log ${CONTENT_LOCATION}/${CONTENT_FILE}
+      env:
+        - name: CONTENT_LOCATION
+          valueFrom:
+            configMapKeyRef:
+              name: configmap01
+              key: content_location
+        - name: CONTENT_FILE
+          valueFrom:
+            configMapKeyRef:
+              name: configmap01
+              key: content_file
+      volumeMounts:
+        - name: internal-volume
+          mountPath: /data01
+  containers:
+    - name: data-server
+      image: docker.io/nginx:1.21.3
+      imagePullPolicy: IfNotPresent
+      ports:
+        - containerPort: 80
+      volumeMounts:
+        - name: internal-volume
+          mountPath: /usr/share/nginx/html
+  volumes:
+    - name: internal-volume
+      emptyDir: {}
+
+---
+apiVersion: v1
+kind: Service
+metadata:
+  # inside the cluster, this service is reachable on the following FQDN:
+  #       "internal-service.nature-rs-system.svc.cluster.local:80"
+  name: internal-service
+  namespace: nature-rs-system
+spec:
+  selector:
+    app: internal-server
+  ports:
+    - targetPort: 80
+      port: 80
+
+---
 apiVersion: apps/v1
 kind: ReplicaSet
 metadata:
@@ -62,7 +123,15 @@ spec:
             - -c
             - |
               cd /data01
-              wget -o log ${CONTENT_LOCATION}/${CONTENT_FILE}
+              count=1
+              while : ; do
+                wget -o log "http://internal-service.nature-rs-system.svc.cluster.local:80/${CONTENT_FILE}"
+                if ( [ -f "${CONTENT_FILE}" ] || [ $count -gt 5 ] ) then break; fi
+                echo "Attempt ${count} at downloading ${CONTENT_FILE}, but failed"
+                sleep 5
+                count=$((count+1))
+              done
+              if ( ! [ -f "${CONTENT_FILE}" ] ) then exit 1; fi
               unzip -q ${CONTENT_FILE}
               rm ${CONTENT_FILE}
               mv pics nature-rs
@@ -71,11 +140,6 @@ spec:
               mkdir nature-rs-podname
               echo "This response, courtesy of pod \"`hostname`\"" > nature-rs-podname/index.html
           env:
-            - name: CONTENT_LOCATION
-              valueFrom:
-                configMapKeyRef:
-                  name: configmap01
-                  key: content_location
             - name: CONTENT_FILE
               valueFrom:
                 configMapKeyRef:
@@ -97,13 +161,6 @@ spec:
               mountPath: /usr/share/nginx/html
             - name: config-volume01
               mountPath: /not-used-for-anything
-          resources:
-            requests:
-              memory: "64Mi"
-              cpu: "250m"
-            limits:
-              memory: "128Mi"
-              cpu: "500m"
         - name: data-server02
           image: docker.io/nginx:1.21.3
           imagePullPolicy: IfNotPresent
@@ -114,13 +171,6 @@ spec:
               mountPath: /usr/share/nginx/html
             - name: config-volume02
               mountPath: /etc/nginx/conf.d
-          resources:
-            requests:
-              memory: "32Mi"
-              cpu: "100m"
-            limits:
-              memory: "128Mi"
-              cpu: "200m"
       volumes:
         - name: vol01
           emptyDir: {}
